spring:
  security:
    oauth2:
      client:
        registration:
          discord:
            client-authentication-method: post
            authorization-grant-type: authorization_code
            client-id: 1023309031214948472
            client-secret: _uUIwd3yMWYGvIKueOmSKCCUMmhWdr6b
            scope:
              - identify
              - guilds
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/discord"
            client-name: mini-ender
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username